MWN/Models/Note.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MWN.Models
{
    public class Note
    {

        public string Id { get; set; }
        public string OwnerId { get; set; }
        [Display(Name="Author")]
        public string Owner { get; set; }
        public string Title { get; set; }
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        //[DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd-MM-yyyy hh:mm}")]
        [Display(Name = "Creation date")]
        [DataType(DataType.DateTime)]
        public DateTime Created { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd-MM-yyyy hh:mm}")]
        public DateTime Changed { get; set; }
        public string NoteAvatar { get; set; }
        //public Note()
        //{
        //    Created= Changed = DateTime.Now;
            
        //}
    }
}

MWN/Controllers/NotesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MWN.Models;
using System.Net;
using System.IO;

namespace MWN.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly MWNContext _context;

        public NotesController(MWNContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index(string OwnerId, string ownerField, string searchString) //search by owner: ownerField , content filter: searchString
        {
            // create LINQ query for furhter owners extraction
            IQueryable<string> ownerQuery = from m in _context.Note
                                            orderby m.Owner
                                            select m.Owner;

            var notes = from m in _context.Note
                        select m; //LINQ query
            notes = notes.Where(x => x.OwnerId == User.FindFirstValue(ClaimTypes.NameIdentifier));   //GET  ONLY OWN NOTES by OwnerId
            if (!String.IsNullOrEmpty(searchString))
            {
                notes = notes.Where(s => s.Content.Contains(searchString) || s.Title.Contains(searchString));
            }

            if(!String.IsNullOrEmpty(ownerField))
            {
                notes = notes.Where(x => x.Owner == ownerField);
            }

            var noteOwnerVM = new NoteOwnerViewModel();
            //noteOwnerVM.owners = new SelectList(await ownerQuery.Distinct().ToListAsync()); //select unique values from owners
            noteOwnerVM.notes = await notes.ToListAsync();

            return View(noteOwnerVM);
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create view

        public IActionResult Create()
        {

            var note = new Note();
            note.OwnerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            note.Owner = this.User.FindFirstValue(ClaimTypes.Name);
            note.Created = note.Changed = DateTime.Now;
            //note.Changed = DateTime.Now;

            _context.Add(note);
            return View(note);
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Owner,OwnerId,Title,Content,Created,Changed")] Note note)
        {
            if (ModelState.IsValid)
            {
                //note.Changed = note.Created= DateTime.Now;
                string noteTitle = note.Title;

                string avatar = GetAvas(noteTitle);
                note.NoteAvatar = avatar;
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        private string GetAvas(string noteTitle)
        {
            // Create a request for the URL. 		
            WebRequest request = WebRequest.Create($"https://avatars.dicebear.com/v2/identicon/{noteTitle}.svg");
            Console.WriteLine(request);
            // If required by the server, set the credentials.
            request.Credentials = CredentialCache.DefaultCredentials;
            // Get the response.
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            // Display the status.
            Console.WriteLine(response.StatusDescription);
            // Get the stream containing content returned by the server.
            Stream dataStream = response.GetResponseStream();
            // Open the stream using a StreamReader for easy access.
            StreamReader reader = new StreamReader(dataStream);
            // Read the content.
            string responseFromServer = reader.ReadToEnd();
            // Display the content.
            // Cleanup the streams and the response.
            reader.Close();
            dataStream.Close();
            response.Close();
            return responseFromServer;
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.SingleOrDefaultAsync(m => m.Id == id);
            //note.Changed = DateTime.Now;

            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string NoteAvatar, [Bind("Id,Owner,OwnerId,Title,Content,Changed,Created,NoteAvatar")] Note note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string noteTitle = note.Title;
                    string avatar = GetAvas(noteTitle);
                    note.NoteAvatar = avatar;
                    note.Changed = DateTime.Now;
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var note = await _context.Note.SingleOrDefaultAsync(m => m.Id == id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(string id)
        {
            return _context.Note.Any(e => e.Id == id);
        }
    }
}

MWN/Views/Notes/Create.cshtml
@model MWN.Models.Note

@{
    ViewData["Title"] = "Create new note";
}

<h2>@ViewBag.Title</h2>

@*<h4>Note</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="OwnerId" class="control-label"></label>
                <input asp-for="OwnerId" class="form-control" />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Owner" class="control-label"></label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" hidden />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Changed" class="control-label"></label>
                <input asp-for="Changed" class="form-control"  />
                <span asp-validation-for="Changed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default btn-primary" />
            
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MWN/Views/Notes/Delete.cshtml
@model MWN.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>Note</h4>*@
    <hr />
    <div style="height:30px;width:30px;">@Html.Raw(Model.NoteAvatar)</div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Changed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Changed)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </form>
</div>

MWN/Views/Notes/Details.cshtml
@model MWN.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>

    @*<h4>Note</h4>*@
    <hr />
    <div style="height:30px;width:30px;">@Html.Raw(Model.NoteAvatar)</div>
    <dl class="dl-horizontal">

        @*<dt>
                @Html.DisplayNameFor(model => model.OwnerId)
            </dt>*@
        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @*@Html.DisplayFor(model => model.Content, additionalViewData: new { htmlAttributes = new { @class = "form-control" } })*@
            <pre>@Html.DisplayFor(model => model.Content)</pre>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Changed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Changed)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id"  class="btn btn-default btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-default btn-info">Back to List</a>
</div>

MWN/Views/Notes/Edit.cshtml
@model MWN.Models.Note

@{
    ViewData["Title"] = "Edit";
}


<h2>Edit your note @Model.Title</h2>

@*<h4>Note</h4>*@
<hr />
<div style="height:30px;width:30px;">@Html.Raw(Model.NoteAvatar)</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" hidden>
                <label asp-for="NoteAvatar" class="control-label"></label>
                <input asp-for="NoteAvatar" class="form-control" />
                <span asp-validation-for="NoteAvatar" class="text-danger"></span>
            </div>
            <div hidden>
                <label asp-for="OwnerId" class="control-label"></label>
                <input asp-for="OwnerId" class="form-control" />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Owner" class="control-label"></label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" hidden />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Changed" class="control-label"></label>
                <input asp-for="Changed" class="form-control" hidden />
                <span asp-validation-for="Changed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default btn-primary" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MWN/Views/Notes/Index.cshtml
@*@model IEnumerable<MWN.Models.Note>*@
@model MWN.Models.NoteOwnerViewModel


@{
    ViewData["Title"] = "Index";
}

<h2>Notes</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<form asp-controller="Notes" asp-action="Index" method="get">
    <p>
        @*<select asp-for="ownerField" asp-items="Model.owners">
            <option value="">All</option>
        </select>*@
        
        Search in notes: <input type="search" name="searchString" />
        <input type="submit" value="Filter" />

        @*Search in content: <input type="search" name="searchString" />
        <input type="submit" value="Filter" />*@
    </p>


</form>
<table class="table">
    <thead>
        <tr>
                <th style="width:30px;">
                    Ava@*@Html.DisplayNameFor(model => model.notes[0].NoteAvatar)*@
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.notes[0].OwnerId)
                </th>*@
                @*<th style="width:50px;">
                    @Html.DisplayNameFor(model => model.notes[0].Owner)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.notes[0].Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.notes[0].Content)
                </th>
                <th>
                    Action
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.notes[0].Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.notes[0].Changed)
                </th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.notes) {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.NoteAvatar)*@
                <div style="height: 30px; width: 30px;">@Html.Raw(item.NoteAvatar)</div>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.OwnerId)
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.Owner)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default btn-primary">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default btn-danger">Delete</a>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Changed)
            </td>*@

        </tr>
}
    </tbody>
</table>